Feature/5 dropdown component
RocketTeamUIT/examify pull request #17
Opened 2022-11-01 01:05 UTC by tuannt02

- Create dropdown component
  - Meet basic needs.
  - Will upgrade later (sub-actions, large, left-icon)
- Hotfix breadcrumb with dark props
- Add dark mode config with tailwind.config.js

2022-11-01 02:27 UTC, PhucHoangVan approved these changes

2022-11-01 04:19 UTC, tuan-hda requested changes
Noice

2022-11-01 04:19 UTC, tuan-hda commented on src/components/ui/ActionsList.jsx
> +ActionsList.propTypes = {
Chỗ này là .defaultProps nha anh zai

2022-11-01 04:19 UTC, tuan-hda commented on src/components/ui/ActionsList.jsx
> +      <ActionItem>Action item 4</ActionItem>
Cái này a zai test hay gì mà có 'Action item 4' á

2022-11-03 02:03 UTC, tuannt02 commented on src/components/ui/ActionsList.jsx
> +      <ActionItem>Action item 4</ActionItem>
Để test thôi azai. Để tạm rồi upgrade lên sau !

2022-11-03 02:04 UTC, tuannt02 commented on src/components/ui/ActionsList.jsx
> +ActionsList.propTypes = {
Tks ! I have already fixed

2022-11-03 02:12 UTC, tuan-hda approved these changes

2022-11-03 02:23 UTC, merged